export const patients = [
  {
    id: 1,
    name: "Arjun Mehta",
    condition: "ACL Reconstruction Recovery",
    score: 82,
    age: 34,
    lastSession: "Today, 9:14 AM",
    streak: 7,
    progress: [55, 60, 58, 67, 71, 75, 82],
    exercises: [1, 2, 3],
    notes: "Patient showing strong improvement. Knee flexion has improved by 18° this week.",
  },
  {
    id: 2,
    name: "Priya Sharma",
    condition: "Rotator Cuff Rehabilitation",
    score: 64,
    age: 28,
    lastSession: "Yesterday, 6:30 PM",
    streak: 3,
    progress: [40, 45, 52, 55, 60, 58, 64],
    exercises: [4, 5],
    notes: "Shoulder abduction needs attention. Compensating with neck movement.",
  },
  {
    id: 3,
    name: "Vikram Nair",
    condition: "Lower Back Pain Management",
    score: 43,
    age: 47,
    lastSession: "3 days ago",
    streak: 0,
    progress: [60, 55, 50, 48, 45, 44, 43],
    exercises: [6, 7],
    notes: "Missed sessions this week. Pain levels reported as 7/10. Review medication.",
  },
  {
    id: 4,
    name: "Sneha Patel",
    condition: "Post-fracture Wrist Therapy",
    score: 91,
    age: 22,
    lastSession: "Today, 11:00 AM",
    streak: 14,
    progress: [70, 74, 78, 82, 86, 89, 91],
    exercises: [8, 9],
    notes: "Excellent recovery. Consider advancing to resistance band exercises.",
  },
  {
    id: 5,
    name: "Rahul Desai",
    condition: "Hip Replacement Recovery",
    score: 58,
    age: 62,
    lastSession: "2 days ago",
    streak: 2,
    progress: [30, 38, 45, 50, 55, 56, 58],
    exercises: [1, 6],
    notes: "Weight bearing tolerance improving. Gait asymmetry still present.",
  },
]

export const exercises = [
  {
    id: 1,
    name: "Knee flexion stretch",
    category: "Knee",
    duration: "3 sets × 12 reps",
    difficulty: "Moderate",
    instructions: "Sit on the edge of a chair. Slowly bend your knee as far as comfortable, hold for 3 seconds, then straighten. Keep your back straight throughout the movement. Focus on a smooth, controlled motion — do not bounce or force the stretch.",
    videoThumb: null,
    status: "pending",
    targetAngle: "90–120°",
    joints: ["Left Knee", "Right Knee", "Left Hip"],
  },
  {
    id: 2,
    name: "Straight leg raise",
    category: "Knee",
    duration: "3 sets × 10 reps",
    difficulty: "Easy",
    instructions: "Lie on your back. Keep one leg straight and lift it to approximately 45°. Hold for 2 seconds at the top. Lower slowly. Keep your core engaged and lower back flat against the surface.",
    videoThumb: null,
    status: "completed",
    targetAngle: "45°",
    joints: ["Left Hip", "Right Hip", "Core"],
  },
  {
    id: 3,
    name: "Terminal knee extension",
    category: "Knee",
    duration: "2 sets × 15 reps",
    difficulty: "Easy",
    instructions: "Stand with a resistance band looped behind your knee. Start with a slight bend in the knee. Contract your quad and straighten the knee fully. Hold 2 seconds and return slowly.",
    videoThumb: null,
    status: "pending",
    targetAngle: "0–15°",
    joints: ["Left Knee", "Right Knee"],
  },
  {
    id: 4,
    name: "Shoulder pendulum",
    category: "Shoulder",
    duration: "3 × 60 seconds",
    difficulty: "Easy",
    instructions: "Lean forward supporting yourself with the unaffected arm on a table. Let the affected arm hang freely. Use momentum from your body to create small circular movements. Do not actively swing — let gravity do the work.",
    videoThumb: null,
    status: "overdue",
    targetAngle: "Free range",
    joints: ["Left Shoulder", "Right Shoulder"],
  },
  {
    id: 5,
    name: "Shoulder blade squeeze",
    category: "Shoulder",
    duration: "3 sets × 10 reps",
    difficulty: "Moderate",
    instructions: "Sit or stand tall. Pull your shoulder blades together as if trying to hold a pencil between them. Hold for 5 seconds. Keep your shoulders down, away from your ears. Do not arch your lower back.",
    videoThumb: null,
    status: "pending",
    targetAngle: "Retraction",
    joints: ["Both Shoulders", "Upper Back"],
  },
  {
    id: 6,
    name: "Pelvic tilt",
    category: "Lower Back",
    duration: "3 sets × 20 reps",
    difficulty: "Easy",
    instructions: "Lie on your back with knees bent. Flatten your lower back against the floor by tightening your abdominal muscles. Hold 5 seconds. Breathe normally throughout — do not hold your breath.",
    videoThumb: null,
    status: "completed",
    targetAngle: "Neutral spine",
    joints: ["Lumbar Spine", "Pelvis"],
  },
  {
    id: 7,
    name: "Cat-camel stretch",
    category: "Lower Back",
    duration: "2 sets × 10 reps",
    difficulty: "Easy",
    instructions: "Start on all fours. Arch your back upward toward the ceiling (cat). Then let it sag toward the floor (camel). Move slowly and smoothly between positions. Keep the movement in your spine, not your hips.",
    videoThumb: null,
    status: "pending",
    targetAngle: "Full spinal range",
    joints: ["Cervical Spine", "Thoracic Spine", "Lumbar Spine"],
  },
  {
    id: 8,
    name: "Wrist flexion and extension",
    category: "Wrist",
    duration: "3 sets × 15 reps",
    difficulty: "Easy",
    instructions: "Hold your arm extended in front of you, palm down. Bend your wrist downward, then upward. Move through the full pain-free range. Keep elbow straight throughout. Use the other hand for gentle overpressure if tolerated.",
    videoThumb: null,
    status: "completed",
    targetAngle: "70° flex / 70° ext",
    joints: ["Left Wrist", "Right Wrist"],
  },
  {
    id: 9,
    name: "Grip strengthening",
    category: "Wrist",
    duration: "3 sets × 12 reps",
    difficulty: "Moderate",
    instructions: "Hold a soft stress ball or rolled towel. Squeeze firmly, hold 3 seconds, then fully release. Ensure complete relaxation between reps. Work within comfortable limits — mild discomfort is acceptable, sharp pain is not.",
    videoThumb: null,
    status: "pending",
    targetAngle: "Max grip",
    joints: ["Hand", "Wrist", "Forearm"],
  },
]

export const feedbackMessages = [
  {
    id: 1,
    from: "Dr. Rajesh Kumar",
    message: "Great session today, Arjun! Your knee flexion angle improved to 95° — a significant improvement from last week's 78°. Keep focusing on the slow, controlled movements during the knee flexion stretch.",
    time: "Today, 9:20 AM",
    unread: true,
  },
  {
    id: 2,
    from: "Dr. Rajesh Kumar",
    message: "I've added the terminal knee extension to your program. Start with light resistance and increase gradually. Let me know if you feel any pain behind the kneecap.",
    time: "Yesterday, 2:15 PM",
    unread: false,
  },
  {
    id: 3,
    from: "Dr. Rajesh Kumar",
    message: "Your 7-day streak is impressive! Consistency is the most important factor in your recovery. Your overall score has increased by 27 points since we started.",
    time: "Mon, 10:00 AM",
    unread: false,
  },
]

export const sessionScoreData = {
  total: 87,
  message: "Excellent session",
  joints: [
    { name: "Left Knee", score: 91, status: "good" },
    { name: "Right Knee", score: 88, status: "good" },
    { name: "Left Hip", score: 84, status: "good" },
    { name: "Right Hip", score: 79, status: "good" },
    { name: "Core alignment", score: 72, status: "warning" },
    { name: "Posture", score: 65, status: "warning" },
  ],
}
